Record_root: 'Record/'

Drone:
  ip : "127.0.0.1"
  speed : 2
  yaw_rate : 15
  depth_threshold : 500

Explore:
  frontier_size : 10
  frontier_divide_size : 30
  explore_range : 60
  obstacle_thick : 1

DroneLift:
  LBE_height: 5
  speed: 2